title: Dhawale Lab
subtitle: The Neuroscience of Exploration
description: We are a research lab at the Centre for Neuroscience within the Indian Institute of Science. We seek to understand how the brain solves complex tasks.
header: images/background.jpg
footer: images/background.jpg
links:
  email: ashesh@iisc.ac.in
  orcid: 0000-0001-7438-1115
  google-scholar: gb2zS_IAAAAJ
  github: dhawale-lab
  twitter: AsheshDhawale
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: ashesh@iisc.ac.in
github: dhawale-lab
twitter: AsheshDhawale
